#ifndef SCENARIOENUM_H
#define SCENARIOENUM_H
enum Scenario {TRACK_CLOSE, TRACK_FAR, TRACK_MANY, FLICK_GRID, FLICK_REACT, FLICK_BOUNCE, SWITCH_360, SWITCH_SEQUENTIAL, SWITCH_GRAVITY};

#endif // SCENARIOENUM_H
